"""Issue #52: path-gated jobs must always report required contexts - a path-skipped required check hangs as "Pending" forever and blocks merge.

Issue #77 adds the generated molecule-matrix axis (scripts/molecule_matrix.py);
the matrix wiring and the aggregate's fail-closed core are pinned here too.
"""

import ast
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
WORKFLOW = yaml.safe_load((ROOT / ".github/workflows/infra-ci.yml").read_text())
JOBS = WORKFLOW["jobs"]

# required_checks in terraform is the branch-protection contract; the workflow
# must satisfy it. Parse the literal list out of the tfvars example.
_tfvars = (ROOT / "terraform/terraform.tfvars.example").read_text()
REQUIRED_CHECKS = ast.literal_eval(
    re.search(r"required_checks\s*=\s*(\[[^\]]*\])", _tfvars).group(1)
)

ALWAYS_AFTER_CHANGES = ["tofu", "tflint", "ansible-lint", "pytest", "molecule"]

# The dorny filter keys (also emitted by the merge-group `all` step);
# molecule_roles is generated by the molecule-matrix step, not a passthrough.
DORNY_FILTERS = {"ansible", "terraform", "pytest"}


def _context_name(key, job):
    # The check context is the job's name: if set, else the job key.
    return job.get("name", key)


def _needs(job):
    # needs: changes parses to str; needs: [a, b] to list - normalize to a set.
    needs = job.get("needs", [])
    if isinstance(needs, str):
        needs = [needs]
    return set(needs)


def test_required_contexts_have_jobs():
    assert REQUIRED_CHECKS, "required_checks parse from tfvars came back empty"
    contexts = {_context_name(key, job) for key, job in JOBS.items()}
    for check in REQUIRED_CHECKS:
        assert check in contexts, f"no job reports required context {check!r}"


def test_pre_commit_never_gated():
    job = JOBS["pre-commit"]
    assert "if" not in job, "pre-commit must never be gated (security hooks)"
    assert "needs" not in job, "pre-commit must never wait on other jobs"


def test_path_gated_jobs_always_run_after_changes():
    for name in ALWAYS_AFTER_CHANGES:
        job = JOBS[name]
        # Exact equality, not a substring: `always() && <condition>` still
        # job-level-skips the required context and wedges merges as Pending.
        assert job.get("if", "").strip() == "always()", (
            f"required context {name} must have job-level if exactly "
            "'always()' - never add conditions; see the header comment in "
            "infra-ci.yml"
        )
        assert "changes" in _needs(job), f"{name}: must need the changes job"


def test_molecule_roles_matrix_is_generated_and_aggregate_gated():
    roles_if = JOBS["molecule-roles"].get("if", "")
    assert "outputs.molecule_roles" in roles_if
    matrix_role = JOBS["molecule-roles"]["strategy"]["matrix"]["role"]
    assert matrix_role == "${{ fromJSON(needs.changes.outputs.molecule_roles) }}"
    aggregate_needs = _needs(JOBS["molecule"])
    assert {"changes", "molecule-roles"} <= aggregate_needs


def test_changes_job_uses_paths_filter():
    assert "changes" in JOBS, "no changes job: path gating is not implemented"
    assert "if" not in JOBS["changes"], (
        "change detection must always run - a gate on it must be a "
        "deliberate, reviewed act"
    )
    uses = [step.get("uses", "") for step in JOBS["changes"].get("steps", [])]
    assert any(u.startswith("dorny/paths-filter@") for u in uses), (
        "changes job must compute outputs via dorny/paths-filter"
    )


def test_changes_outputs_wiring_is_closed():
    # Renaming a filter or outputs key resolves to "" with no error and
    # permanently pins RUN_JOB=false on PRs - silent green. Close the loop:
    # references, outputs keys, dorny filter keys and the merge-group `all`
    # step's emitted keys must be the same set (molecule_roles excepted - it
    # is generated by the molecule-matrix step, not a dorny/all passthrough).
    raw = (ROOT / ".github/workflows/infra-ci.yml").read_text()
    referenced = set(
        re.findall(r"needs\.changes\.outputs\.([A-Za-z_][A-Za-z0-9_]*)", raw)
    )
    assert referenced == DORNY_FILTERS | {"molecule_roles"}, (
        f"unexpected needs.changes.outputs.* references: {sorted(referenced)}"
    )
    outputs = JOBS["changes"]["outputs"]
    for key in referenced:
        assert key in outputs, (
            f"changes job has no output {key!r} but other jobs reference it"
        )
    for key in DORNY_FILTERS:
        # Two producers, exactly one active per event: dorny on
        # pull_request/push, the `all` step on merge_group. The output must
        # pass through BOTH same-named step outputs in this order - dorny's
        # 'false' is a non-empty (truthy) string that short-circuits ||, a
        # skipped step emits empty (falsy) and falls through.
        expected = (
            "${{ steps.filter.outputs." + key + " || steps.all.outputs." + key + " }}"
        )
        assert outputs[key] == expected, (
            f"changes.outputs.{key} must be exactly {expected!r}, "
            f"got {outputs[key]!r}"
        )
        # A == 'false' consumer breaks the merge-group side: `all` never emits
        # 'false', and an empty left side would silently skip required work.
        assert not re.search(
            r"needs\.changes\.outputs\." + key + r"\s*==\s*'false'", raw
        ), f"needs.changes.outputs.{key} must never be compared == 'false'"
    # molecule_roles is generated by the molecule-matrix step, not dorny.
    assert outputs["molecule_roles"] == (
        "${{ steps.molecule-matrix.outputs.molecule_roles }}"
    )
    assert any(
        s.get("id") == "molecule-matrix" for s in JOBS["changes"]["steps"]
    ), "changes job needs a molecule-matrix step producing molecule_roles"
    filter_step = next(
        s for s in JOBS["changes"]["steps"] if s.get("id") == "filter"
    )
    filters = yaml.safe_load(filter_step["with"]["filters"])
    all_step = next(
        s for s in JOBS["changes"]["steps"] if s.get("id") == "all"
    )
    all_keys = set(re.findall(r'echo "([A-Za-z_][A-Za-z0-9_]*)=true"', all_step["run"]))
    assert '} >> "$GITHUB_OUTPUT"' in all_step["run"], (
        "the all step emits its outputs through one grouped redirect to "
        "$GITHUB_OUTPUT (SC2129) - without it the outputs never land"
    )
    assert set(outputs) == referenced, (
        f"changes.outputs keys drifted from the references: {sorted(outputs)}"
    )
    assert DORNY_FILTERS == set(filters) == all_keys, (
        "dorny filter keys, all-step emitted keys and the dorny "
        "needs.changes.outputs.* references drifted: "
        f"filters={sorted(filters)} all={sorted(all_keys)}"
    )


def test_workflow_triggers_merge_group():
    # ADR 0053: the merge queue drives required checks via the merge_group
    # event. Dropping this trigger stalls every queued merge as Pending
    # forever - the required contexts would never report on the group.
    triggers = WORKFLOW.get("on", WORKFLOW.get(True))  # bare `on:` parses as True
    assert "merge_group" in triggers


def test_infra_ci_runs_nightly_full_matrix():
    # The nightly schedule is the full-matrix drift tripwire (moving base
    # image tag, galaxy collection bumps) behind the per-PR scoping.
    triggers = WORKFLOW.get("on", WORKFLOW.get(True))  # bare `on:` parses as True
    assert "schedule" in triggers, (
        "infra-ci needs the nightly schedule - the full-matrix drift tripwire"
    )
    assert any("cron" in entry for entry in triggers["schedule"]), (
        "schedule trigger must carry a cron entry"
    )


def test_molecule_matrix_diff_enumerates_rename_paths():
    # git's diff.renames defaults to true: a bare --name-only collapses a
    # role->role rename to the destination path (under-scoped matrix) and a
    # role->outside rename to [] (green aggregate, zero scenarios run).
    step = next(
        s for s in JOBS["changes"]["steps"] if s.get("id") == "molecule-matrix"
    )
    assert "git diff --no-renames --name-only" in step["run"], (
        "the molecule-matrix diff must enumerate both sides of a rename"
    )


def test_molecule_aggregate_fail_closed_core_is_pinned():
    # The required "molecule" context's legitimacy rule is string-pinned: a
    # skip is green exactly when the scoped matrix is empty; a skipped matrix
    # with a non-empty role list, failed change detection, or a failed image
    # build fails closed.
    run = next(
        s
        for s in JOBS["molecule"]["steps"]
        if s.get("name") == "All molecule scenarios must have passed"
    )["run"]
    assert '[ "$CHANGES_RESULT" = "success" ]' in run
    assert '[ "$MOLECULE_ROLES" = "[]" ]' in run
    assert '[ "$IMAGE_RESULT" = "failure" ]' in run
    assert (
        'echo "gating bug: molecule-roles skipped with a non-empty matrix'
        ' - failing closed"' in run
    )


def test_merge_group_runs_everything():
    # ADR 0053: a merge group is the exact tree entering main - path-gating is
    # a pull_request-only optimization. On merge groups dorny is skipped (it
    # has no diff anchors there) and the `all` step reports every area changed.
    steps = JOBS["changes"]["steps"]
    filter_step = next(s for s in steps if s.get("id") == "filter")
    assert filter_step.get("if", "").strip() == "github.event_name != 'merge_group'"
    all_step = next(s for s in steps if s.get("id") == "all")
    assert all_step.get("if", "").strip() == "github.event_name == 'merge_group'"
    # The molecule matrix admits merge groups through the generator: the
    # molecule-matrix step runs ungated on every event, and the script emits
    # all roles for any non-pull_request event (pinned in
    # tests/test_molecule_matrix.py).
    matrix_step = next(s for s in steps if s.get("id") == "molecule-matrix")
    assert "if" not in matrix_step


# Issue #76: the molecule test image is built once per run by an image job
# and shared with the matrix via artifact - matrix legs load, never build.
# A second image one day (another distro base) extends IMAGE_BUILD_JOBS.
IMAGE_BUILD_JOBS = ["molecule-image"]
IMAGE_TAG = "localhost/fedora44-systemd:latest"
IMAGE_ARTIFACT = "fedora44-systemd"


def _run_steps(job):
    return [s.get("run", "") for s in job.get("steps", [])]


def test_molecule_image_built_once_and_shared():
    image_jobs = [JOBS[name] for name in IMAGE_BUILD_JOBS]
    roles = JOBS["molecule-roles"]

    # A job-level-if-gated job as a required check never reports and wedges
    # every merge as Pending - image jobs must never join required_checks.
    for name in IMAGE_BUILD_JOBS:
        assert name not in REQUIRED_CHECKS

    # The image jobs and the matrix share one gate, string-equal: divergence
    # either wastes a build per ansible-unchanged PR or reds seven legs on a
    # missing artifact.
    for name in IMAGE_BUILD_JOBS:
        assert JOBS[name].get("if", "").strip() == roles.get("if", "").strip(), (
            f"{name} gate must equal molecule-roles gate"
        )
        assert "changes" in _needs(JOBS[name])

    # The matrix waits on every image job; the aggregate sees them too.
    assert set(IMAGE_BUILD_JOBS) <= _needs(roles)
    assert set(IMAGE_BUILD_JOBS) <= _needs(JOBS["molecule"])

    # Matrix legs never build; builds live only in image jobs.
    for step_run in _run_steps(roles):
        assert "podman build" not in step_run
    for key, job in JOBS.items():
        builds = [r for r in _run_steps(job) if "podman build" in r]
        if key in IMAGE_BUILD_JOBS:
            assert len(builds) == 1, f"{key} must hold the single image build"
            assert "ansible/molecule/fedora44-systemd.Containerfile" in builds[0]
            assert f"-t {IMAGE_TAG}" in builds[0]
        else:
            assert not builds, f"{key} must not podman build"

    # The artifact contract: same name on upload and download, save/load tar
    # filenames agree, and every molecule scenario references the built tag.
    uploads = [
        s for name in IMAGE_BUILD_JOBS for s in JOBS[name].get("steps", [])
        if s.get("uses", "").startswith("actions/upload-artifact@")
    ]
    downloads = [
        s for s in roles.get("steps", [])
        if s.get("uses", "").startswith("actions/download-artifact@")
    ]
    assert len(uploads) == 1 and len(downloads) == 1
    assert uploads[0]["with"]["name"] == downloads[0]["with"]["name"] == IMAGE_ARTIFACT
    save = [r for r in _run_steps(JOBS[IMAGE_BUILD_JOBS[0]]) if "podman save" in r]
    load = [r for r in _run_steps(roles) if "podman load" in r]
    assert len(save) == 1 and len(load) == 1
    tar_name = re.search(r"(\S+\.tar)", save[0]).group(1).strip('"').rsplit("/", 1)[-1]
    # ${{ runner.temp }} and "$RUNNER_TEMP" are the same directory; a
    # subdirectory edit on either side must fail here, not at runtime.
    assert uploads[0]["with"]["path"] == "${{ runner.temp }}/" + tar_name
    assert downloads[0]["with"]["path"] == "${{ runner.temp }}"
    assert f'"$RUNNER_TEMP/{tar_name}"' in load[0]

    molecule_yamls = sorted(ROOT.glob("ansible/roles/*/molecule/*/molecule.yml"))
    assert molecule_yamls, "no molecule scenarios found"
    for path in molecule_yamls:
        doc = yaml.safe_load(path.read_text())
        images = {p["image"] for p in doc["platforms"]}
        assert images == {IMAGE_TAG}, f"{path}: platforms must use {IMAGE_TAG}"
        for p in doc["platforms"]:
            assert p.get("pre_build_image") is True, (
                f"{path}: pre_build_image must stay true - the podman driver "
                "must not build its own layer per leg"
            )
